name: minesweeper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  shared_preferences: 2.2.2
  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2719.1
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_ui_auth: ^1.13.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.1
  cloud_firestore: ^4.15.8
  adaptive_theme: ^3.6.0

dev_dependencies:
  flutter_hooks: ^0.18.0 
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf