// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEsx8HfLsDcX501k-zMLQQQjiJuE-d_Og',
    appId: '1:694186317814:web:b986efa966d9ed345ad9d7',
    messagingSenderId: '694186317814',
    projectId: 'flutter-minesweeper-d7574',
    authDomain: 'flutter-minesweeper-d7574.firebaseapp.com',
    storageBucket: 'flutter-minesweeper-d7574.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_pAQgj-vK2N2hVxd4sQHFPcsnGfRmgg',
    appId: '1:694186317814:android:7a5c03e006e16ba75ad9d7',
    messagingSenderId: '694186317814',
    projectId: 'flutter-minesweeper-d7574',
    storageBucket: 'flutter-minesweeper-d7574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqFCB4GeikuR3nQiCkx45C7n8xOmQr4KY',
    appId: '1:694186317814:ios:f7b84ca21e95f7015ad9d7',
    messagingSenderId: '694186317814',
    projectId: 'flutter-minesweeper-d7574',
    storageBucket: 'flutter-minesweeper-d7574.appspot.com',
    iosBundleId: 'com.example.minesweeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqFCB4GeikuR3nQiCkx45C7n8xOmQr4KY',
    appId: '1:694186317814:ios:2b9cda669b1d94aa5ad9d7',
    messagingSenderId: '694186317814',
    projectId: 'flutter-minesweeper-d7574',
    storageBucket: 'flutter-minesweeper-d7574.appspot.com',
    iosBundleId: 'com.example.minesweeper.RunnerTests',
  );
}
